switching back to mysql action to test

diff --git a/.github/workflows/ci-test.yml b/.github/workflows/ci-test.yml
--- a/.github/workflows/ci-test.yml
+++ b/.github/workflows/ci-test.yml
@@ -7,17 +7,17 @@ on:
 jobs:
   integration-tests:
     runs-on: ubuntu-20.04
-    services:
-      mysql:
-        image: mysql:5.7
-        env:
-          MYSQL_USER: test
-          MYSQL_PASSWORD: test
-          MYSQL_DATABASE: irida_integration_test
-          MYSQL_ROOT_PASSWORD: root
-        ports:
-          - 3306
-        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
+    #services:
+    #  mysql:
+    #    image: mysql:5.7
+    #    env:
+    #      MYSQL_USER: test
+    #      MYSQL_PASSWORD: test
+    #      MYSQL_DATABASE: irida_integration_test
+    #      MYSQL_ROOT_PASSWORD: root
+    #    ports:
+    #      - 3306
+    #    options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
     strategy:
       fail-fast: false  #Setting so that if one of the test suites fail, the other will continue
@@ -37,6 +37,16 @@ jobs:
         with:
           path: '**/node_modules'
           key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
+
+      - uses: mirromutth/mysql-action@v1.1
+        with:
+          host port: 3800 # Optional, default value is 3306. The port of host
+          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
+          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
+          mysql version: '5.7' # Optional, default value is "latest". The version of the MySQL
+          mysql database: 'irida_integration_test' # Optional, default value is "test". The specified database which will be create
+          mysql user: 'test' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
+          mysql password: 'test' # Required if "mysql user" exists. The password for the "mysql user"
       #- name: Start database # Starts mysql on the server
       #  run: sudo /etc/init.d/mysql start
       #- name: 'Database setup' # Creates the database and user for the tests
@@ -47,11 +57,11 @@ jobs:
           java-version: 11
       - name: Verify MySQL connection
         run: |
-          while ! mysqladmin ping -h"127.0.0.1" -P3306 --silent; do
+          while ! mysqladmin ping -h"127.0.0.1" -P3800 --silent; do
             sleep 1
           done
       - name: Install libraries # Install our non-maven backed dependencies, and docs requirements
         run: pushd lib; ./install-libs.sh; popd; sudo gem install jekyll; sudo gem install pygments.rb
       - name: Run tests with Maven # Run the test suite
-        run: ./run-tests.sh --db-host 127.0.0.1 --db-port 3306 ${{ matrix.suite }}
+        run: ./run-tests.sh --db-host 127.0.0.1 --db-port 3800 ${{ matrix.suite }}
 
